name: Deno

env:
  SBUS_URL: ${{ secrets.SBUS_URL }}
  SBUS_POLICY_NAME: ${{ secrets.SBUS_POLICY_NAME }}
  SBUS_POLICY_KEY: ${{ secrets.SBUS_POLICY_KEY }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
